import { Vehicle } from '../types';

interface DocTemplateOptions {
  vehicle: Vehicle;
  companyName?: string;
  companyAddress?: string;
  date?: string;
}

const getHeaderHtml = (companyName: string = 'DOCKS (PVT) LTD', companyAddress: string = 'Karachi, Pakistan') => `
<div style="text-align: center; border-bottom: 2px solid #b45309; padding-bottom: 15px; margin-bottom: 25px;">
  <h1 style="color: #b45309; font-family: Arial, sans-serif; font-size: 24pt; margin: 0; text-transform: uppercase; letter-spacing: 1px;">
    ${companyName}
  </h1>
  <p style="color: #4b5563; font-family: Arial, sans-serif; font-size: 10pt; margin: 5px 0 0 0;">
    Customs Bonded Carrier | Afghan Transit Trade | TIR Logistics Operations
  </p>
  <p style="color: #6b7280; font-family: Arial, sans-serif; font-size: 9pt; margin: 3px 0 0 0;">
    ${companyAddress} | Tel: +92-21-34567890 | Email: info@dockspvt.com
  </p>
</div>
`;

const getFooterHtml = () => `
<div style="margin-top: 40px; padding-top: 15px; border-top: 1px solid #e5e7eb; text-align: center; font-family: Arial, sans-serif; font-size: 8pt; color: #9ca3af;">
  This is an official document generated by DOCKS (PVT) LTD ERP System. Valid with authorized company seal and signatures.
</div>
`;

const triggerDocDownload = (htmlContent: string, filename: string) => {
  const fullDocument = `
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head>
      <meta charset="utf-8">
      <title>${filename}</title>
      <!--[if gte mso 9]>
      <xml>
        <w:WordDocument>
          <w:View>Print</w:View>
          <w:Zoom>100</w:Zoom>
          <w:DoNotOptimizeForBrowser/>
        </w:WordDocument>
      </xml>
      <![endif]-->
      <style>
        @page {
          size: A4 portrait;
          margin: 20mm 20mm 20mm 20mm;
          mso-header-margin: 36pt;
          mso-footer-margin: 36pt;
        }
        body {
          font-family: 'Times New Roman', Times, serif;
          font-size: 12pt;
          line-height: 1.5;
          color: #000000;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin: 15px 0;
        }
        table, th, td {
          border: 1px solid #333333;
        }
        th {
          background-color: #f3f4f6;
          font-weight: bold;
          padding: 8px;
          text-align: left;
        }
        td {
          padding: 8px;
        }
        .signature-section {
          margin-top: 40px;
          page-break-inside: avoid;
        }
      </style>
    </head>
    <body>
      ${htmlContent}
    </body>
    </html>
  `;

  const blob = new Blob(['\ufeff', fullDocument], {
    type: 'application/msword'
  });

  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

// 1. Lease Agreement (6 Months Lease between Owner and DOCKS (PVT) LTD with 2 witnesses)
export const generateLeaseAgreementDoc = (options: DocTemplateOptions) => {
  const { vehicle, companyName = 'DOCKS (PVT) LTD', date = new Date().toLocaleDateString('en-GB') } = options;
  const owner = vehicle.ownerName || 'Vehicle Owner';
  const ownerCnic = vehicle.ownerCnic || '_________________';
  const ownerAddress = vehicle.ownerAddress || '_____________________________________';

  const html = `
    ${getHeaderHtml(companyName)}
    <h2 style="text-align: center; text-decoration: underline; font-family: Arial, sans-serif; font-size: 15pt; margin-bottom: 20px;">
      COMMERCIAL VEHICLE LEASE AGREEMENT (6 MONTHS)
    </h2>

    <p>This Commercial Vehicle Lease Agreement is executed on this day <strong>${date}</strong> at Karachi, Pakistan by and between:</p>

    <p>
      <strong>1. ${owner}</strong>, holding CNIC No. <strong>${ownerCnic}</strong>, resident of ${ownerAddress} (hereinafter referred to as the <strong>"LESSOR / OWNER"</strong>, which expression shall include his legal heirs, successors, and assigns of the FIRST PART).
    </p>

    <p style="text-align: center; font-weight: bold; margin: 10px 0;">AND</p>

    <p>
      <strong>2. ${companyName}</strong>, a licensed Customs Bonded Carrier and Multi-Modal Logistics Company having its registered office at Karachi (hereinafter referred to as the <strong>"LESSEE / OPERATOR"</strong> of the SECOND PART).
    </p>

    <h3 style="font-family: Arial, sans-serif; font-size: 12pt; margin-top: 15px;">PARTICULARS OF LEASED VEHICLE:</h3>
    <table>
      <tr>
        <th width="35%">Registration Number:</th>
        <td><strong>${vehicle.registrationNumber}</strong></td>
      </tr>
      <tr>
        <th>Engine Number:</th>
        <td>${vehicle.engineNo || 'N/A'}</td>
      </tr>
      <tr>
        <th>Chassis Number:</th>
        <td>${vehicle.chassisNo || 'N/A'}</td>
      </tr>
      <tr>
        <th>Make & Model:</th>
        <td>${vehicle.makeModel || 'Heavy Transport Vehicle'}</td>
      </tr>
      <tr>
        <th>Category / Fleet Type:</th>
        <td>${vehicle.category} (${vehicle.size || '40ft'})</td>
      </tr>
      <tr>
        <th>DPL Serial Code:</th>
        <td>${vehicle.dplSerial || 'N/A'}</td>
      </tr>
    </table>

    <h3 style="font-family: Arial, sans-serif; font-size: 12pt; margin-top: 15px;">TERMS & CONDITIONS:</h3>
    <ol style="margin-left: 20px; line-height: 1.6;">
      <li><strong>Period of Lease:</strong> This agreement is valid for a period of <strong>Six (06) Months</strong> commencing from <strong>${date}</strong>.</li>
      <li><strong>Customs Registration:</strong> The Lessor hereby authorizes the Lessee to register the said vehicle with Pakistan Customs under Bonded Carrier rules, Afghan Transit, and TIR transport conventions.</li>
      <li><strong>Operation & Dispatch:</strong> The vehicle shall be deployed exclusively for lawful transport of imported/export and transit goods assigned by the Lessee.</li>
      <li><strong>Compliance & Route Fitness:</strong> The Lessor guarantees that the vehicle is mechanically fit, properly insured, and adheres to all National Highway Authority (NHA) axle-load regulations.</li>
      <li><strong>Driver Responsibility:</strong> Appointed driver (${vehicle.driverName || 'Authorized Driver'}, CNIC: ${vehicle.driverCnic || 'N/A'}) shall strictly follow customs escort, tracking, and port-gate protocol.</li>
    </ol>

    <div class="signature-section" style="margin-top: 50px;">
      <table style="border: none; margin-top: 30px;">
        <tr style="border: none;">
          <td style="border: none; width: 50%; vertical-align: top;">
            <p style="margin-bottom: 50px;"><strong>LESSOR / OWNER:</strong></p>
            <p>Signature: __________________________</p>
            <p>Name: <strong>${owner}</strong></p>
            <p>CNIC: ${ownerCnic}</p>
            <p>Thumb Impression: __________________</p>
          </td>
          <td style="border: none; width: 50%; vertical-align: top;">
            <p style="margin-bottom: 50px;"><strong>FOR ${companyName}:</strong></p>
            <p>Signature: __________________________</p>
            <p>Authorized Signatory / Fleet Manager</p>
            <p>Official Seal & Stamp</p>
          </td>
        </tr>
      </table>

      <h4 style="margin-top: 35px; border-bottom: 1px solid #cccccc; padding-bottom: 5px;">WITNESSES:</h4>
      <table style="border: none; margin-top: 10px;">
        <tr style="border: none;">
          <td style="border: none; width: 50%;">
            <p><strong>WITNESS 1:</strong></p>
            <p>Name: _______________________________</p>
            <p>CNIC: _______________________________</p>
            <p>Signature: __________________________</p>
          </td>
          <td style="border: none; width: 50%;">
            <p><strong>WITNESS 2:</strong></p>
            <p>Name: _______________________________</p>
            <p>CNIC: _______________________________</p>
            <p>Signature: __________________________</p>
          </td>
        </tr>
      </table>
    </div>
    ${getFooterHtml()}
  `;

  triggerDocDownload(html, `Lease_Agreement_${vehicle.registrationNumber.replace(/\s+/g, '_')}.doc`);
};

// 2. Customs Registration Request on Company Letterhead
export const generateCustomsRegistrationRequestDoc = (options: DocTemplateOptions) => {
  const { vehicle, companyName = 'DOCKS (PVT) LTD', date = new Date().toLocaleDateString('en-GB') } = options;

  const html = `
    ${getHeaderHtml(companyName)}
    <p style="text-align: right; margin-bottom: 20px;">
      <strong>Ref:</strong> DPL/CUST/REG/${vehicle.registrationNumber.replace(/\s+/g, '-')}/${new Date().getFullYear()}<br>
      <strong>Date:</strong> ${date}
    </p>

    <p style="line-height: 1.4;">
      <strong>To,</strong><br>
      The Assistant / Deputy Collector of Customs,<br>
      Bonded Carrier Licensing Section / Afghan Transit / Preventive,<br>
      Custom House, Karachi.
    </p>

    <h3 style="text-align: center; text-decoration: underline; margin: 25px 0 15px 0;">
      SUBJECT: REQUEST FOR REGISTRATION OF BONDED CARRIER VEHICLE IN WEBOC SYSTEM - REG NO: ${vehicle.registrationNumber}
    </h3>

    <p>Respected Sir,</p>

    <p>
      With utmost respect, it is submitted that <strong>${companyName}</strong> is a licensed Customs Bonded Carrier operating under valid License issued by the Directorate General of Transit Trade and Federal Board of Revenue (FBR).
    </p>

    <p>
      In order to cater to increased transhipment and transit traffic from Karachi Sea Ports to Upcountry Dry Ports and Border Customs Stations, we have inducted the following heavy commercial vehicle into our fleet under valid lease agreement:
    </p>

    <table>
      <tr>
        <th width="30%">Vehicle Registration No:</th>
        <td><strong>${vehicle.registrationNumber}</strong></td>
      </tr>
      <tr>
        <th>Category / Purpose:</th>
        <td><strong>${vehicle.category}</strong></td>
      </tr>
      <tr>
        <th>Chassis Number:</th>
        <td>${vehicle.chassisNo || 'N/A'}</td>
      </tr>
      <tr>
        <th>Engine Number:</th>
        <td>${vehicle.engineNo || 'N/A'}</td>
      </tr>
      <tr>
        <th>Owner Name & CNIC:</th>
        <td>${vehicle.ownerName || 'N/A'} (${vehicle.ownerCnic || 'N/A'})</td>
      </tr>
      <tr>
        <th>Driver Name & CNIC:</th>
        <td>${vehicle.driverName || 'N/A'} (${vehicle.driverCnic || 'N/A'})</td>
      </tr>
      <tr>
        <th>Satellite Tracker Status:</th>
        <td>Installed & Operational (Authorized Tracking Vendor)</td>
      </tr>
    </table>

    <p>
      All requisite attested documents including Vehicle Registration Book, Fitness Certificate, Route Permit, Owner CNIC, Driver License, and Lease Agreement are enclosed herewith for your perusal.
    </p>

    <p>
      It is therefore requested that the above-mentioned vehicle may kindly be registered / enrolled in the WeBOC Customs Database as a Bonded Carrier vehicle under our carrier code to enable smooth issuance of Transhipment Permits (TP) and Carrier Manifests.
    </p>

    <p>We assure our utmost compliance with all Customs rules and statutory regulations.</p>

    <div class="signature-section" style="margin-top: 50px;">
      <p>Yours faithfully,</p>
      <p style="margin-top: 40px;"><strong>For ${companyName}</strong></p>
      <p>Authorized Signatory / Managing Director</p>
      <p>Encl: As Stated Above</p>
    </div>
    ${getFooterHtml()}
  `;

  triggerDocDownload(html, `Customs_Registration_Request_${vehicle.registrationNumber.replace(/\s+/g, '_')}.doc`);
};

// 3. Vehicle Renewal Request to Customs
export const generateCustomsRenewalRequestDoc = (options: DocTemplateOptions) => {
  const { vehicle, companyName = 'DOCKS (PVT) LTD', date = new Date().toLocaleDateString('en-GB') } = options;

  const html = `
    ${getHeaderHtml(companyName)}
    <p style="text-align: right; margin-bottom: 20px;">
      <strong>Ref:</strong> DPL/CUST/REN/${vehicle.registrationNumber.replace(/\s+/g, '-')}/${new Date().getFullYear()}<br>
      <strong>Date:</strong> ${date}
    </p>

    <p style="line-height: 1.4;">
      <strong>To,</strong><br>
      The Assistant / Deputy Collector of Customs,<br>
      Bonded Carrier Licensing Authority,<br>
      Custom House, Karachi.
    </p>

    <h3 style="text-align: center; text-decoration: underline; margin: 25px 0 15px 0;">
      SUBJECT: REQUEST FOR EXTENSION / RENEWAL OF BONDED REGISTRATION FOR VEHICLE NO: ${vehicle.registrationNumber}
    </h3>

    <p>Respected Sir,</p>

    <p>
      We would like to bring to your kind notice that our fleet vehicle bearing Registration No. <strong>${vehicle.registrationNumber}</strong> (DPL Serial: <strong>${vehicle.dplSerial || 'N/A'}</strong>) is registered with your esteemed department as an active Bonded Carrier vehicle.
    </p>

    <p>
      The current bonded enrollment period for this vehicle is expiring on <strong>${vehicle.validationExpiryDate || 'Upcoming Expiry'}</strong>. The vehicle lease agreement and mechanical fitness have been duly renewed for an additional period of six months.
    </p>

    <table>
      <tr>
        <th width="35%">Vehicle Registration No:</th>
        <td><strong>${vehicle.registrationNumber}</strong></td>
      </tr>
      <tr>
        <th>Engine & Chassis:</th>
        <td>${vehicle.engineNo || 'N/A'} / ${vehicle.chassisNo || 'N/A'}</td>
      </tr>
      <tr>
        <th>Previous Approval Validity:</th>
        <td>${vehicle.validationStartDate || 'N/A'} to ${vehicle.validationExpiryDate || 'N/A'}</td>
      </tr>
      <tr>
        <th>Requested Renewal Period:</th>
        <td>Six (06) Months with effect from current expiry</td>
      </tr>
      <tr>
        <th>Tracker Status:</th>
        <td>Active & Monitored 24/7</td>
      </tr>
    </table>

    <p>
      Enclosed please find fresh Motor Vehicle Inspection Fitness Certificate, renewed Lease Agreement, and Tracker Functionality Certificate for your ready reference.
    </p>

    <p>
      Kindly accord your kind approval for the renewal of the vehicle's validity in the Customs WeBOC portal.
    </p>

    <div class="signature-section" style="margin-top: 50px;">
      <p>Thanking you in anticipation,</p>
      <p style="margin-top: 40px;"><strong>For ${companyName}</strong></p>
      <p>Authorized Signatory / Fleet Manager</p>
    </div>
    ${getFooterHtml()}
  `;

  triggerDocDownload(html, `Customs_Renewal_Request_${vehicle.registrationNumber.replace(/\s+/g, '_')}.doc`);
};

// 4. Vehicle Cancellation Request / NOC Release on Company Letterhead
export const generateCustomsCancellationNocDoc = (options: DocTemplateOptions) => {
  const { vehicle, companyName = 'DOCKS (PVT) LTD', date = new Date().toLocaleDateString('en-GB') } = options;

  const html = `
    ${getHeaderHtml(companyName)}
    <p style="text-align: right; margin-bottom: 20px;">
      <strong>Ref:</strong> DPL/NOC/DEL/${vehicle.registrationNumber.replace(/\s+/g, '-')}/${new Date().getFullYear()}<br>
      <strong>Date:</strong> ${date}
    </p>

    <p style="line-height: 1.4;">
      <strong>To,</strong><br>
      The Deputy Collector of Customs,<br>
      Bonded Carrier Section / Transit Trade Directorate,<br>
      Custom House, Karachi.
    </p>

    <h3 style="text-align: center; text-decoration: underline; margin: 25px 0 15px 0;">
      SUBJECT: REQUEST FOR DE-REGISTRATION / DE-LINKING AND ISSUANCE OF NOC FOR VEHICLE NO: ${vehicle.registrationNumber}
    </h3>

    <p>Respected Sir,</p>

    <p>
      This is with reference to the vehicle bearing Registration No. <strong>${vehicle.registrationNumber}</strong>, Chassis No. <strong>${vehicle.chassisNo || 'N/A'}</strong>, registered under Bonded Carrier operations of <strong>${companyName}</strong>.
    </p>

    <p>
      We hereby state and certify that:
    </p>

    <ul style="margin-left: 20px; line-height: 1.6;">
      <li>The vehicle owner has mutually settled all accounts and requested release of the vehicle from our bonded carrier fleet.</li>
      <li>All transhipment goods, containers, and consignments previously carried by this vehicle have been safely delivered to their respective destination dry ports / border customs stations without any shortage or discrepancy.</li>
      <li>There are <strong>NO OUTSTANDING LIABILITIES, CUSTOMS INQUIRIES, OR PENDING GDs</strong> against this vehicle under our company.</li>
    </ul>

    <p>
      In view of the above, <strong>${companyName}</strong> has <strong>NO OBJECTION (NOC)</strong> to the cancellation and de-linking of Vehicle No. <strong>${vehicle.registrationNumber}</strong> from our Bonded Carrier WeBOC profile.
    </p>

    <p>
      It is kindly requested that the vehicle may be cancelled from our bonded list and returned to open status.
    </p>

    <div class="signature-section" style="margin-top: 50px;">
      <p>Respectfully submitted,</p>
      <p style="margin-top: 40px;"><strong>For ${companyName}</strong></p>
      <p>Managing Director / Authorized Carrier Signatory</p>
      <p>Official Stamp & Seal</p>
    </div>
    ${getFooterHtml()}
  `;

  triggerDocDownload(html, `Vehicle_Cancellation_NOC_${vehicle.registrationNumber.replace(/\s+/g, '_')}.doc`);
};
